name: Daily Quiz Update (Self-Hosted)
permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *' # UTC 00:00 -> KST 09:00
  workflow_dispatch: {}

jobs:
  update:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm ci --ignore-scripts --no-audit --no-fund || true

      - name: Update quiz via Ollama
        env:
          OLLAMA_BASE_URL: http://localhost:11434
          OLLAMA_MODEL: qwen2.5:7b-instruct
        run: |
          npm run update:quiz

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: daily quiz update (self-hosted)" || echo "No changes to commit"

      - name: Push changes
        if: success()
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

